### ISSUE TITLE
Trouble to begin with the plugin

### ISSUE THREAD

**Issue by XyroDp59** [yllen/geststock#21]
Hey, i'm new with glpi and have to setup this plugin. 
Even if there is a "stock" status for my computers like in the plugin config menu, there isn't any computers in the geststock tab.
Sorry for the bad english, i'm french and my glpi too so i tried to translate it as well as i could.

Thanks for the help !

PS: sorry for the bad quality, i don't know why it is so bad

![image](https://user-images.githubusercontent.com/81575508/112855046-be849000-90ae-11eb-8706-b8d2dabe6a8e.png)
![image](https://user-images.githubusercontent.com/81575508/112855081-c6dccb00-90ae-11eb-95d1-d4d17366fc36.png)
![image](https://user-images.githubusercontent.com/81575508/112855115-cfcd9c80-90ae-11eb-813d-94dddc06cbc1.png)

**Comment by yllen** [comment]
Pas de problème, je suis française aussi.
Pour voir les éléments réservables, il faut cliquer sur le lien Voir le stock
La liste au dessous listera les réservations créées ; donc tant que vous n'aurez pas cliqué sur le + pour créer une réservation, cette liste sera vide.

**Comment by yllen** [comment]
Pas de nouvelles ? je clos
