### ISSUE TITLE
GLPI 9.2.x: Can't install plugin

### ISSUE THREAD

**Issue by okvok** [yllen/geststock#7]
Hello,
I tried to install plugin, but it can't be installed ((
After press INSTALL I see only:
![image](https://user-images.githubusercontent.com/20252855/35860565-98069158-0b55-11e8-9e00-3c9bff81787d.png)

and nothing happen.
Could you help me please.

**Comment by ykoffi16** [comment]
I have this problem

**Comment by nicolas62** [comment]
Hello,
I have this problem too.
I have a blank page when I try to install the plugin.

**Comment by yllen** [comment]
Release was only done for 9.1.X
I will make the release for 9.2.x very soon

**Comment by pathic** [comment]
I have a problem when install the plugin. Here is error message from web server,
PHP Fatal error:  Cannot make static method CommonDBTM::getSearchOptionstoAdd() non static in class PluginGeststockFollowup in /var/www/html/glpi/plugins/geststock/inc/followup.class.php on line 0, referer: /glpi/front/plugin.php

**Comment by vv0rk** [comment]
I have this problem too.

**Comment by yllen** [comment]
No problem for me with version in master branch
